-- =========================================================================
-- SCRIPT DE BASE DE DATOS SUPABASE (PostgreSQL)
-- Plataforma: Espacio Seguro - Concienciación y Apoyo contra el Acoso
-- =========================================================================

-- 1. Crear la tabla de experiencias
CREATE TABLE IF NOT EXISTS public.experiencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    tipo_acoso VARCHAR(50) NOT NULL CHECK (tipo_acoso IN ('escolar', 'laboral', 'cibernetico', 'otro')),
    relato TEXT NOT NULL,
    fecha DATE NOT NULL,
    anonimo BOOLEAN NOT NULL DEFAULT true,
    alias VARCHAR(100) DEFAULT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'publicado', 'rechazado')),
    apoyos_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- 2. Crear índices para acelerar las consultas públicas y de moderación
CREATE INDEX IF NOT EXISTS idx_experiencias_estado_created ON public.experiencias (estado, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_experiencias_tipo ON public.experiencias (tipo_acoso);

-- 3. Habilitar Seguridad a Nivel de Fila (Row Level Security - RLS)
ALTER TABLE public.experiencias ENABLE ROW LEVEL SECURITY;

-- 4. Política: Lectura pública solo de testimonios con estado 'publicado'
DROP POLICY IF EXISTS "Lectura pública de experiencias publicadas" ON public.experiencias;
CREATE POLICY "Lectura pública de experiencias publicadas"
ON public.experiencias
FOR SELECT
USING (estado = 'publicado');

-- 5. Política: Inserción pública (cualquier usuario anónimo puede enviar su testimonio,
--    pero obligatoriamente se inserta con estado 'pendiente')
DROP POLICY IF EXISTS "Inserción pública con estado pendiente" ON public.experiencias;
CREATE POLICY "Inserción pública con estado pendiente"
ON public.experiencias
FOR INSERT
WITH CHECK (estado = 'pendiente');

-- 6. Política para permitir que el contador de apoyos se actualice anónimamente
DROP POLICY IF EXISTS "Permitir actualizar contador de apoyos" ON public.experiencias;
CREATE POLICY "Permitir actualizar contador de apoyos"
ON public.experiencias
FOR UPDATE
USING (estado = 'publicado')
WITH CHECK (estado = 'publicado');

-- 7. Política permisiva de moderación para permitir aprobar/rechazar desde la interfaz web:
DROP POLICY IF EXISTS "Permitir moderacion para administradores" ON public.experiencias;
CREATE POLICY "Permitir moderacion para administradores"
ON public.experiencias
FOR ALL
USING (true)
WITH CHECK (true);

-- 8. Datos iniciales de ejemplo (con estado 'publicado')
INSERT INTO public.experiencias (titulo, tipo_acoso, relato, fecha, anonimo, alias, estado, apoyos_count, created_at)
VALUES 
(
    'Aprender a poner límites en la preparatoria',
    'escolar',
    'Durante mi primer año de preparatoria, un grupo de compañeros comenzó a burlarse de mi forma de vestir y a esconder mis útiles todos los días. Al principio guardé silencio por miedo a que fuera peor, pero el estrés empezó a afectar mi salud. Un día decidí contárselo a una profesora de confianza y a mi madre. Juntas acudimos con la dirección escolar. Aunque el proceso tomó tiempo, la intervención de los docentes y el apoyo de mi familia me devolvieron la tranquilidad. Comparto esto para recordarte que pedir ayuda no te hace débil; es el primer paso para proteger tu bienestar.',
    '2024-03-15',
    true,
    NULL,
    'publicado',
    14,
    NOW() - INTERVAL '3 days'
),
(
    'Superando el ciberacoso y recuperando mi espacio digital',
    'cibernetico',
    'Crearon un perfil falso en redes sociales usando mis fotos para difundir rumores falsos. Me sentí profundamente vulnerable y aislada. Decidí no responder a las provocaciones, guardé capturas de pantalla de todo como evidencia y reporté la cuenta en la plataforma. Además, hablé con la Línea de la Vida para recibir contención emocional porque la ansiedad no me dejaba dormir. Me ayudó mucho desconectarme por unos días y rodearme de amigos reales. Hoy sé que lo que otros digan en una pantalla no define quién soy.',
    '2024-05-20',
    false,
    'Camila R.',
    'publicado',
    28,
    NOW() - INTERVAL '2 days'
),
(
    'Hacer frente a la intimidación y sobrecarga laboral',
    'laboral',
    'En mi trabajo anterior, un supervisor utilizaba comentarios despectivos y me excluía de reuniones importantes de manera deliberada. Empecé a registrar cada incidente con fecha, hora y correos de respaldo. Cuando la situación fue insostenible, presenté el reporte ante Recursos Humanos con las pruebas organizadas. Aunque decidí cambiar de empleo meses después, el proceso me enseñó a reconocer el acoso laboral a tiempo y a no normalizar ningún tipo de maltrato en el entorno profesional.',
    '2024-08-10',
    true,
    NULL,
    'publicado',
    9,
    NOW() - INTERVAL '1 day'
);